spring:
  application:
    name: wfengine
    
  profiles:
   active: cloud
  cloud:
    config:
      uri: http://configservice.apps.wwtlabs.net
flyway:
  baseline-on-migrate: true
eureka:
  client:
    service-url:
      defaultZone: http://serviceregistry.apps.wwtlabs.net/eureka
      register-with-eureka: false
      
  instance:
    prefer-ip-address: true
