configuration:  
  projectName: workflow-ms
server:
  port: 8000
message:
  greeting: Hello from the wfengine!
  
spring:  
  application:
         name: workflow-ms
  profiles:
       active: cloud
  cloud:
    config:
      uri: http://configservice.apps.wwtlabs.net
  logging:
     file: logs/WFEngine-logging.log
