configuration: 
  projectName: workflow-ms
message: 
  greeting: "Hello from the wfengine!"
server: 
  port: 8000
spring: 
  application: 
    name: workflow-ms
  cloud: 
    config: 
      uri: "http://configservice.apps.wwtlabs.net"
  logging: 
    file: logs/WFEngine-logging.log
  profiles: 
    active: cloud
