configuration: 
  projectName: workflow-ms
eureka: 
  client: 
    service-url: 
      defaultZone: "http://serviceregistry.apps.wwtlabs.net/eureka"
      register-with-eureka: false
message: 
  greeting: "Hello from the wfengine!"
server: 
  port: 8000
spring: 
  application: 
    name: workflow-ms
  cloud: 
    config: 
      uri: "http://configservice.apps.wwtlabs.net"
  logging: 
    file: logs/WFEngine-logging.log
  profiles: 
    active: cloud
