configuration: 
  projectName: wfengine
logging: 
  file: logs/WFEngineCloud-logging.log
message: 
  greeting: "Hello from the wfengine cloud!"
server: 
  port: 8000
spring: 
  profiles: cloud
