eureka: 
  client: 
    service-url: 
      defaultZone: "http://localhost:8761/eureka"
server: 
  context-path: /edge
  port: 8000
spring: 
  application: 
    name: edgeservice
  cloud: 
    config: 
      uri: "http://localhost:8888"
  mvc: 
    dispatch-options-request: true
