--- 
configuration: 
  projectName: wfengine
logging: 
  file: logs/WFEngineDev-logging.log
message: 
  greeting: "Hello from the wfengine default!"
server: 
  port: 8000
spring: 
  profiles: default
