configuration:  
  projectName: workflow-ms
server:
  port: 8000
message:
  greeting: Hello from the wfengine!
  
spring:  
  application:
    name: workflow-ms
  profiles:
   active: default
  logging:
    file: ./logs/WFEngine-logging.log
