spring:
  application:
    name: wfengine
    
  profiles:
    active: dev
    
  cloud:
    config:
      uri: http://localhost:8888
      
flyway:
  baseline-on-migrate: true
  
eureka:
  client:
    service-url:
      defaultZone: http://serviceregistry.apps.wwtlabs.net/eureka
      register-with-eureka: false
      
  instance:
    prefer-ip-address: true
