configuration: 
  projectName: wfengine
logging: 
  file: logs/WFEngineDev-logging.log
message: 
  greeting: "Hello from the wfengine dev!"
server: 
  port: 8000
spring:
  profiles:
    active: dev
