--- 
configuration: 
  projectName: wfengine
message: 
  greeting: "Hello from the wfengine dev!"
server: 
  port: 8000
spring: 
  application: 
    name: wfengine
  logging: 
    file: logs/WFEngine-logging.log
