--- 
configuration: 
  projectName: wfengine
message: 
  greeting: "Hello from the dev environment!"
server: 
  port: 8000
spring: 
  application: 
    name: wfengine
  cloud: 
    config: 
      uri: "http://localhost:8888"
