spring:
  application:
    name: workflow-ms
    
  profiles:
    active: dev
    
  cloud:
    config:
      uri: 
  rabbitmq:
    host: 10.100.1.79
    port: 15672
    username: guest
    password: guest
  redis:
    host: 10.100.1.79
    port: 6379
    password: guest
  datasource:
    url: jdbc:mysql://10.100.1.79:3306/wfengine?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
