--- 
spring: 
  application: 
    name: wfengine
  cloud: 
    config: 
      uri: ~
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: "jdbc:mysql://10.100.1.79:3306/wfengine?autoReconnect=true&useSSL=false"
    username: root
  profiles: 
    active: dev
  rabbitmq: 
    host: "10.100.1.79"
    password: guest
    port: 15672
    username: guest
  redis: 
    host: "10.100.1.79"
    password: guest
    port: 6379
---
configuration: 
  projectName: workflow-ms
message: 
  greeting: "Hello from the wfengine!"
server: 
  port: 8000
spring: 
  application: 
    name: workflow-ms
  logging: 
    file: logs/WFEngine-logging.log
  profiles: 
    active: dev
